#!/bin/bash

if [ $# -eq 2 ]; then
  DNS=$1
  SRV=$2
else
  DNS=$(kubectl -n kube-system get svc -l k8s-app==kube-dns -o json | jq -r '.items[].spec.clusterIP')
  SRV=$1
fi

INFO=$(dig +short @${DNS} $SRV SRV)
if [ "$INFO X" == " X" ]; then
    >&2 echo "Unable to resolve service"
    exit 1
fi

HOST=$(dig +short @${DNS} $(echo $INFO | cut '-d ' -f4))
PORT=$(echo $INFO | cut '-d ' -f3)
echo $HOST:$PORT
