kind: PersistentVolume
apiVersion: v1
metadata:
  name: mariadb
  labels:
    type: local
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  hostPath:
    path: "/data/mariadb"
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: wordpress
  labels:
    type: local
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  hostPath:
    path: "/data/wordpress"
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: mariadb-backup
  labels:
    type: local
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  hostPath:
    path: "/data/mariadb-backup"
